packageExtensions:
  '@codemirror/lang-jinja@*':
    peerDependencies:
      '@codemirror/state': '*'
      '@codemirror/view': '*'
  '@codemirror/language-data@*':
    dependencies:
      '@codemirror/state': '*'
      '@codemirror/view': '*'
